version: 2

project_name: teakit

before:
  hooks:
    - go mod tidy

builds:
  - id: teakit
    main: ./cmd/teakit
    binary: teakit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  github:
    owner: SlateLH
    name: teakit
